### PR TITLE
Customizable data folder

### PR DESCRIPTION
**Pull request by quantumsheep**
Useful for Docker volumes and data management.

### CODE REVIEW

**Comment by chung1905** [comment]
I like this PR so much.
 Put code and data in the same directory makes it really hard to mount docker volumn

**Comment by nanashj** [comment]
image

**Comment by nanashj** [comment]
>

**Comment by nanashj** [comment]
#

**Review by nanashj — APPROVED** [review]

**Comment by quantumsheep** [comment]
This PR is now useless since commit https://github.com/edeng23/binance-trade-bot/commit/30f681939803ccf73a11b71b92a4494d574da416 as it uses the `data` directory for storage.

**Pull request closed without merging**
