### PR TITLE
Modifications

### PR DESCRIPTION
**Pull request by BenQoder**
* Added Ability To Auto Select Coin If Current Coin Not Specified In user.cfg
* Remove supported coins from main code and added another file for easy modification without modifying main bot code
* Make telegram bot work only if the Telegram token is set
* Added code to make bot start with USDT Balance
* ~~Added code to Skip when ALTCOIN + USDT pair does not exist on Binance~~
* Better code to format JSON data on Telegram Bot

### CODE REVIEW

**Comment by edeng23** [comment]
Why did you remove the ignoring of unsupported pairs?

**Comment by BenQoder** [comment]
image

I started getting the above errors after running Bot for long and I believe that's what caused it.

I will improve on the code and create another PR to that effect.

**Comment by edeng23** [comment]
I understand. I wonder why this happens since you did check if the coin price is None before calling float(). I'll take a look into it. 
Other than that the code looks good, I like how you organised the Telegram message content. 
Also, putting the coin list in a file makes much more sense :)

**Comment by ivanpavlina** [comment]
In supported coin list file QTM should be QTUM, app is failing with above error because of that.

**Comment by edeng23** [comment]
@ivanpavlina Fixed.

**Comment by ivanpavlina** [comment]
Also, shouldn't there be a check if initial coin is already purchased? 
ATM I have DOGE bought (no USDT available in wallet) and in user.cfg.ini i have set current_coin=DOGE

After initialization app is trying to buy DOGE which fails.

```2021-02-16 08:41:20,812 - crypto_trader_logger - INFO - Initializing BTT vs OMG
2021-02-16 08:41:21,080 - crypto_trader_logger - INFO - Initializing BTT vs BTT
2021-02-16 08:41:21,080 - crypto_trader_logger - INFO - Done initializing, generating file
2021-02-16 08:41:21,081 - crypto_trader_logger - INFO - Purchasing DOGE to begin trading
2021-02-16 08:41:22,969 - crypto_trader_logger - INFO - BUY QTY 0.0
2021-02-16 08:41:23,505 - crypto_trader_logger - INFO - APIError(code=-1013): Invalid quantity.
2021-02-16 08:41:25,118 - crypto_trader_logger - INFO - APIError(code=-1013): Invalid quantity.
2021-02-16 08:41:26,674 - crypto_trader_logger - INFO - APIError(code=-1013): Invalid quantity.```

**Comment by edeng23** [comment]
@ivanpavlina I added the check.

**Pull request merged**
