### PR TITLE
Update multiple_coins_strategy.py

### PR DESCRIPTION
**Pull request by werim**
Solution to type error for multiple_coins_strategy.

### CODE REVIEW

**Comment by Blaklis** [comment]
This is not how it should be patched. The scouting message should only dispaly coin instead of current_coin.

**Comment by rel-s** [comment]
Hi, please update this PR with some more information. An informative title, some text detailing what you fixed - perhaps even linking to a related issue if there is one? thanks!

**Comment by Blaklis** [comment]
This PR intended to patch the error on multiple_coins strategy with `current_coin` being printed, which sometimes leads to a `NoneType` being concatenated to a string.

This PR now have multiple commits that is not related to the initial fix that was provided - surely because it's a PR from the author master branch. The fix was also incorrect, so I guess this can be closed now.

**Comment by rel-s** [comment]
Yep, closing.

**Pull request closed without merging**
