### PR TITLE
WIP: Elon bot

### PR DESCRIPTION
**Pull request by jamielaff**
## WIP
- [x] Reimplement class from existing repo
- [x] Remove BRIDGE usage, run with current_coin
- [x] Move into its own strategy
- [ ] Hook up properly with DB
- [ ] Unit tests
- [ ] Personal tests

### CODE REVIEW

**Comment by erenatas** [comment]
When manipulation becomes a reality...

**Comment by Blaklis** [comment]
Would be better if it's implemented as a new strategy instead ?

**Comment by jamielaff** [comment]
> Would be better if it's implemented as a new strategy instead ?

Could be - it'll probably be a very long time between executions though 😄 
I'm also not sure on the behaviour if you have this + default/multi strategy running. Thoughts?

**Comment by geeks121** [comment]
this bot should be added for strategy

**Comment by rel-s** [comment]
This definitely won't be merged as a default behaviour. Perhaps as another strategy, although this deviates pretty far from the bot's original purpose...

**Pull request closed without merging**
