### PR TITLE
Revert renaming of `alt_coin` and `crypto_coin` variables

### PR DESCRIPTION
**Pull request by j-waters**
I appreciate what this commit was trying to do, and maybe the names could be improved, but the names as they stand don't actually make sense. I was working on #196 and kept getting confused. There is no target or origin, just the two halves of the trading pair.

The original name made sense because traditionally, a trading pair will have a more established 'crypto' coin, and a less popular 'alt' coin. It is still confusing since all the coins are crypto coins, but I think it makes more sense than `origin` and `target`, since half the time they're the wrong way round anyway.

### CODE REVIEW

**Comment by edeng23** [comment]
I completely agree with you on the matter, I also got confused when playing around with the "buy" function. That being said, I don't think that "crypto" and "alt" are indicative enough. Why not use "origin" and "target"  in the logical order?

**Comment by j-waters** [comment]
That would make slightly more sense, although I do think the emphasis should really be on the trading pair rather than the individual coins. [This article](https://www.gemini.com/cryptopedia/what-are-cryptocurrency-pairs) uses the term 'base', so maybe we say `alt_coin` and `base_coin`? Or `target_coin` and `base_coin`? I guess `base` is similar to origin now that I think about it.

Maybe we could change it so that the buy and sell methods accept `Pair`s instead.

So instead of `buy(Coin('XLM'),Coin( 'USDT'))` and `sell(Coin('USDT'), Coin('XLM'))` it would be `buy(Pair('XLM', 'USDT')`, etc.

Then again maybe it doesn't really matter! This isn't exactly high priority just something I noticed while developing

**Comment by edeng23** [comment]
I think that for readability, giving the symbols names is important. I find that when reading the order_quantity calculation, which is quite complicated as is, having the idea of the coin you're starting from and coin you want to end up with helps. 
Using Pairs sounds like the standard way to go, addressing the coins as "from_coin" and "to_coin".

**Comment by rel-s** [comment]
I think we should close this and perhaps open a new issue discussing future namings - do comment if you think we should keep this PR open.

**Pull request closed without merging**
